# NumPy: Numerical Computing

##### Week 1 - Day 3

This notebook covers 4 basic Python exercises:
1. Creating a 2D **array** of shape (4, 4) filled with values 1-16 and print its shape and dtype.
2. Using **slicing** to extract the second column and the last row.
3. Using a **boolean mask** to select all values greater than the array's mean.
4. Adding a 1D row array to every row of a 2D array using **broadcasting** and verify the result manually.
> Note: Words written in bold represents key topics that were studied and covered during the day.

In [3]:
import numpy as np

## Exercise 1

In [13]:
array = np.arange(1, 17).reshape(4, 4)  # arange(1, 17); to 17 because we need to 16 (last number not included).

print("Array:\n", array)
print("Array Shape:", array.shape)
print("Array Data Type:", array.dtype)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Array Shape: (4, 4)
Array Data Type: int64


## Exercise 2

In [15]:
column_2 = array[:, 1]   # (:) means all rows, 2nd column
last_row = array[-1, :]  # last row, all rows

print("Second Column:", column_2)
print("Last Row:", last_row)

Second Column: [ 2  6 10 14]
Last Row: [13 14 15 16]


## Exercise 3

In [19]:
array_mean = array.mean()
values_greater_than_mean = array[array > array_mean]

print("Mean:", array_mean)
print("Values Greater than Mean:", values_greater_than_mean)

Mean: 8.5
Values Greater than Mean: [ 9 10 11 12 13 14 15 16]


## Exercise 4

In [22]:
row = np.array([1, 2, 3, 4])  # 1D array
broadcasting = array + row    # adding row variable to all rows - broadcasting -.

print("Row:", row)
print("Result:\n", broadcasting)

Row: [1 2 3 4]
Result:
 [[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]
 [14 16 18 20]]


In [25]:
manual_test = array[0] + row

print("Array[0]:", array[0])
print("Row:", row)
print("Manual Result:", manual_test)
print("Manual Result Matches Broadcasting Result?", np.array_equal(manual_test, broadcasting[0]))

Array[0]: [1 2 3 4]
Row: [1 2 3 4]
Manual Result: [2 4 6 8]
Manual Result Matches Broadcasting Result? True
